packages:
  - packages/*
  - apps/*

catalog:
  '@types/node': ^25.4.0
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@tailwindcss/postcss': '^4.2.1'
  clsx: ^2.1.1
  cross-env: ^10.0.0
  react: ^19.2.4
  react-dom: ^19.2.4
  tailwindcss: ^4.2.1
  typescript: 5.9.3

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
